---
abstract: 'RT Extension for custom ticket notification'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-NotificationMatrix
no_index:
  directory:
    - html
    - inc
    - t
requires:
  perl: 5.10.1
version: '3.0'
x_module_install_rtx_version: '0.37'
x_requires_rt: 4.2.0
